[package]
name = "server"
version = "0.1.0"
edition = "2024"

[features]
tui = ["ratatui", "crossterm", "crossbeam", "chrono"]

[dependencies]
bevy.workspace = true
shared.workspace = true
avian3d.workspace = true
# tui
ratatui = { workspace = true, optional = true}
crossterm = { workspace = true, optional = true}
crossbeam = { workspace = true, optional = true}
chrono = { workspace = true, optional = true}
# networking
serde.workspace = true
aeronet.workspace = true
aeronet_webtransport = { workspace = true, features = ["server"] }
aeronet_replicon = { workspace = true, features = ["server"] }
bevy_replicon = { workspace = true, features = ["server"] }
