[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
shared.workspace = true
serde.workspace = true
aeronet.workspace = true
aeronet_webtransport = { workspace = true, features = ["server"] }
aeronet_replicon = { workspace = true, features = ["server"] }
bevy_replicon = { workspace = true, features = ["server"] }
